# Generated by Django 2.2.3 on 2019-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
