# Generated by Django 2.2.3 on 2019-07-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend_status'),
        ('events', '0004_attend_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_invited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_friends', to='users.Friend'),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='got_invited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Invite'),
        ),
    ]
