# Generated by Django 2.2.3 on 2019-07-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190701_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='invited_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_to', to='events.Invite'),
        ),
    ]
