# Generated by Django 2.2.3 on 2019-07-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20190702_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='invited_to',
        ),
        migrations.AddField(
            model_name='event',
            name='invited_to',
            field=models.ManyToManyField(null=True, related_name='invited_to', through='events.Invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
